class StaticFiles:

    @staticmethod
    def get(file_path):

        file_path = file_path.replace("\\", "/")

        files = {

            ".gitignore": """__pycache__/
*.pyc
.venv/
venv/
.env
.vscode/
.idea/
node_modules/
dist/
build/
""",

            "requirements.txt": """# Python dependencies

prettytable
""",

            "README.md": """# Project

Generated by Jarvis AI

## Features

- AI Generated
- Professional Structure
- Ready to Run
"""

        }

        return files.get(file_path)